include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart, lib/**.config.dart]
  
linter:
  rules:
    public_member_api_docs: false
    use_setters_to_change_properties: false
    always_put_required_named_parameters_first: false
